### ISSUE TITLE
Getting error while running baseline & 3.1 

### ISSUE THREAD

**Issue by omyokun** [sarahwie/attention#7]
Hi, thank you for providing the code, but while running the following command "./run_baselines.sh imdb" and same thing for "./run_frozen_attn.sh imdb"  I got the following error:

Traceback (most recent call last):
  File "/Users/mycomputer/code/Transparency/train_and_run_experiments_bc.py", line 83, in <module>
    train_dataset_on_encoders(dataset, args, exp_name)
  File "/Users/mycomputer/code/Transparency/ExperimentsBC.py", line 21, in train_dataset_on_encoders
    train_dataset(dataset, args, exp_name)
  File "/Users/mycomputer/code/Transparency/ExperimentsBC.py", line 6, in train_dataset
    trainer = Trainer(dataset, args, config=config)
  File "/Users/mycomputer/code/Transparency/Trainers/TrainerBC.py", line 10, in __init__
    self.model = Model(config, args, pre_embed=dataset.vec.embeddings)
  File "/Users/mycomputer/code/Transparency/model/Binary_Classification.py", line 30, in __init__
    self.encoder = Encoder.from_params(Params(configuration['model']['encoder'])).to(device)
  File "/Users/mycomputer/.pyenv/versions/3.9.0/lib/python3.9/site-packages/allennlp/common/params.py", line 196, in __init__
    self.params = _replace_none(params)
  File "/Users/mycomputer/.pyenv/versions/3.9.0/lib/python3.9/site-packages/allennlp/common/params.py", line 574, in _replace_none
    params[key] = _replace_none(value)
  File "/Users/mycomputer/.pyenv/versions/3.9.0/lib/python3.9/site-packages/allennlp/common/params.py", line 570, in _replace_none
    if params == "None":
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The error comes from this line of code  "Params(configuration['model']['encoder'])". I've tried to do some modifications to make Param work, but I still get the same error. 

Thank you in advance for your reply.

**Comment by yuvalpinter** [comment]
Hi,

It looks like the problem is in whatever you're passing as a `configuration` object, which is populated by a configuration file. Also notice that the error is not in this module, but in AllenAI's code which initializes the `Params` object.
Can you take a look at that?

- Yuval
